// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhN76eISb9zbt5XaVp7o8kSljs17vMRFQ',
    appId: '1:895566844932:web:8123814b62a65ccd9c9151',
    messagingSenderId: '895566844932',
    projectId: 'madhurjya-to-do',
    authDomain: 'madhurjya-to-do.firebaseapp.com',
    storageBucket: 'madhurjya-to-do.firebasestorage.app',
    measurementId: 'G-NJNXMCC3X5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmKeFCr0xVVVQDuofr-TMd3iUuPI2rUbI',
    appId: '1:895566844932:android:347052166c09e1a99c9151',
    messagingSenderId: '895566844932',
    projectId: 'madhurjya-to-do',
    storageBucket: 'madhurjya-to-do.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAflKFOUjz2cWAkx2_bgATVKYc_V9bctAM',
    appId: '1:895566844932:ios:97b457ba48d513999c9151',
    messagingSenderId: '895566844932',
    projectId: 'madhurjya-to-do',
    storageBucket: 'madhurjya-to-do.firebasestorage.app',
    iosBundleId: 'com.example.test1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAflKFOUjz2cWAkx2_bgATVKYc_V9bctAM',
    appId: '1:895566844932:ios:97b457ba48d513999c9151',
    messagingSenderId: '895566844932',
    projectId: 'madhurjya-to-do',
    storageBucket: 'madhurjya-to-do.firebasestorage.app',
    iosBundleId: 'com.example.test1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhN76eISb9zbt5XaVp7o8kSljs17vMRFQ',
    appId: '1:895566844932:web:9b6da3d152fa96b99c9151',
    messagingSenderId: '895566844932',
    projectId: 'madhurjya-to-do',
    authDomain: 'madhurjya-to-do.firebaseapp.com',
    storageBucket: 'madhurjya-to-do.firebasestorage.app',
    measurementId: 'G-Y70R6N2RKF',
  );
}
